[23기 최호정] ADD : list페이지 레이아웃
wecode-bootcamp-korea/23-1st-Weeteweete-frontend pull request #9
Opened 2021-08-04 05:15 UTC by jjung-developer

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-04 09:04 UTC, younuk23 commented
리뷰 요청하시는 거면 리뷰요청 라벨 및 PR 본문 작성해주세요!

2021-08-05 06:36 UTC, younuk23 commented
@jjung-developer 리뷰 요청하시는 거면 리뷰요청 라벨 및 PR 본문 작성해주세요!

2021-08-06 04:56 UTC, younuk23 reviewed
리뷰 확인 및 수정해주세요

2021-08-06 04:56 UTC, younuk23 commented on src/pages/Product/ColorChip.js
> +  render() {
변수선언부와 메소드 선언부는 한줄 공백 주는게 가독성측면에서 좋아보입니다.

2021-08-06 04:56 UTC, younuk23 commented on src/pages/Product/ColorChip.js
> +  };
className은 스타일링을 주기 위한 목적이지 이렇게 로직에 포함되면 목적과 걸맞지 않고, 추후 유지보수에 어려움이 있을 수 있습니다.
필요한 정보가 color값이라면 color를 인자로 받는 식으로 처리하면 되겠네요!

2021-08-06 04:56 UTC, younuk23 commented on src/pages/Product/ColorChip.js
> +    return this.props.uniqueColor.map(el => {
el이라는 광범위함 변수명보다 이 자리에 어떤 값이 담길건지 이름에서 드러나는 값으로 매개변수 명 설정해주는게 좋습니다!
수정해주세요

2021-08-06 04:56 UTC, younuk23 commented on src/pages/Product/Product.js
> +    fetch('data/ListItemData.json')
```suggestion
    fetch('/data/ListItemData.json')
```
절대경로 붙여주세요 안그럴경우 현재 위치한 url 기준으로 계산하기 때문에 오동작 할 여지가 있습니다.

2021-08-06 04:56 UTC, younuk23 commented on src/pages/Product/Prolist.js
> +    const newArray = [...selectColor];
newArray라는 광범위한 이름보다는 의미가 특정되는 정확한 네이밍 해주세요

2021-08-06 04:56 UTC, younuk23 commented on src/pages/Product/Prolist.js
> +          });
이 부분은 어떤 동작을 의도한 건가요? 코멘트로 남겨주세요!

2021-08-06 04:56 UTC, younuk23 commented on src/pages/Product/Prolist.js
> +        {prolist.map((el, index) => {
여기도 el말고 네이밍 정확하게 해주세요

2021-08-06 04:56 UTC, younuk23 commented on src/pages/Product/Prolist.js
> +                      })}
`selectColor` props의 전달여부만 조건에 따라서 결정짓는 것 같은데 전체적으로 삼항 안쓰고 해당 props 전달 여부만 조건부 처리해도 충분해보입니다.

2021-08-06 06:47 UTC, jjung-developer commented on src/pages/Product/Prolist.js
> +          });
안녕하세요 ! 연욱님 😇
해당 코드는 colorChip이 표출되는 부분에서 중복되는 color를 제외해서 배열에 담기위한 코드입니다!

2021-08-06 09:48 UTC, younuk23 approved these changes
Approve

2021-08-06 09:48 UTC, younuk23 commented on src/pages/Product/Prolist.js
> +          });
```
          const colorArr = el.information.map(el => el.color);
          const uniqueColor = el.information.filter((el, i) => {
            return colorArry.indexOf(el.color) === i;
          });
```
- push 동작을 동시에 할 필요 없이 map이용해서 color만 있는 배열 만들 수 있어 보입니다.
- 또는 Set이라는 자료구조를 활용하는 방법도 괜찮습니다!
- 여러 방법 있으니 찾아보시고, 참고해보시면 좋겠습니다!
코멘트 참고해보시고, 수정은 다음 작업하실 때 해주면 되겠습니다. 이 브랜치는 머지하겠습니다!

2021-08-06 09:48 UTC, younuk23 commented
Conflict 해결해주세요, Approve 해뒀으니까 해결 후 셀프 머지 진행해주세요!

2021-08-09 01:25 UTC, younuk23 commented
아직 해결 안되서 다시 Request Change 상태로 변경하겠습니다, 컨플릭트 해결하시면 제가 Approve 하고 머지할게요!

2021-08-09 01:25 UTC, younuk23 requested changes
아직 해결 안되서 다시 Request Change 상태로 변경하겠습니다, 컨플릭트 해결하시면 제가 Approve 하고 머지할게요!

2021-08-09 07:55 UTC, jjung-developer commented
충돌해결했습니다!

2021-08-09 08:32 UTC, merged

2021-08-09 08:32 UTC, younuk23 commented
호정님 라벨 바꿔주셔야지 제가 확인합니다! Conflict 발생 라벨 그대로 붙어있으면 제가 확인 안하고 넘어갈수도 있어서 라벨 잘 바꿔주세요! 일단 이건 머지했습니다!